[package]
name = "rust-idcard"
version = "0.1.2"
authors = ["Su Yu <suyu@intermaker.cn>"]
edition = "2018"
license = "MIT"
description = "Verifier for Chinese ID Card."
repository = "https://github.com/suyuxp/rust-idcard"

[dependencies]
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
